# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-01 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workform', '0002_workformmodel_it_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workformmodel',
            name='it_check',
            field=models.CharField(choices=[('yes', '需要'), ('no', '不需要')], default='no', max_length=10, verbose_name='是否需要IT审计'),
        ),
    ]
