# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workform', '0003_auto_20180601_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workformtypemodel',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='工单类型名称'),
        ),
    ]
