# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 16:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sqlmanager', '0003_auto_20180613_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlrollbackmodel',
            name='rollback_exec_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='执行人'),
        ),
    ]
