# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmanager', '0007_auto_20180619_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inceptionbackgroundmodel',
            name='inc_backup_ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='IPv4', verbose_name='Inception 备份服务器IP'),
        ),
        migrations.AlterField(
            model_name='inceptionbackgroundmodel',
            name='inc_backup_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inception 备份服务器密码'),
        ),
        migrations.AlterField(
            model_name='inceptionbackgroundmodel',
            name='inc_backup_port',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Inception 备份服务器端口'),
        ),
        migrations.AlterField(
            model_name='inceptionbackgroundmodel',
            name='inc_backup_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Inception 备份服务器账号'),
        ),
        migrations.AlterUniqueTogether(
            name='inceptionbackgroundmodel',
            unique_together=set([('inc_ip', 'inc_port')]),
        ),
    ]
