# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-19 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmanager', '0008_auto_20180619_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='inceptionbackgroundmodel',
            name='inc_status',
            field=models.CharField(choices=[('active', '启用'), ('stop', '停用')], default='stop', max_length=10, verbose_name='Inception 配置状态'),
        ),
        migrations.AddField(
            model_name='inceptiondangersqlmodel',
            name='status',
            field=models.CharField(choices=[('active', '启用'), ('stop', '停用')], default='stop', max_length=10, verbose_name='该规则是否启用'),
        ),
    ]
