# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-25 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmanager', '0011_auto_20180623_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlrollbackmodel',
            name='rollback_sql_sha1',
            field=models.CharField(max_length=100, null=True, verbose_name='sql的sha1'),
        ),
    ]
