# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-27 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmanager', '0014_auto_20180626_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='sqlexecdetailmodel',
            name='sql_type',
            field=models.CharField(max_length=50, null=True, verbose_name='sql的类型:insert,update,delete,alter...'),
        ),
    ]
