# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-02 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sqlmanager', '0015_sqlexecdetailmodel_sql_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sqldetailmodel',
            options={'ordering': ['id'], 'permissions': (('sql_exec', '能够执行/回滚 SQL'), ('dba_add_sql', 'DBA可以提交 SQL')), 'verbose_name': 'SQL记录表'},
        ),
    ]
