# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-18 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResultRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=500, verbose_name='task 名称')),
                ('task_id', models.CharField(max_length=500, verbose_name='task id')),
            ],
            options={
                'verbose_name': 'task_name 与 task_id 映射表',
                'db_table': 'task_result_record',
                'ordering': ['-id'],
            },
        ),
    ]
