# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-06 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workform', '__first__'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRulesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_hostname', models.CharField(blank=True, max_length=100, null=True, verbose_name='原主机名')),
                ('s_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='源IP')),
                ('d_hostname', models.CharField(blank=True, max_length=100, null=True, verbose_name='目标主机名')),
                ('d_ip', models.GenericIPAddressField(protocol='IPv4', verbose_name='目标IP')),
                ('d_port', models.CharField(max_length=100, verbose_name='目标端口')),
                ('protocol', models.CharField(max_length=100, verbose_name='网络协议')),
                ('app_name', models.CharField(max_length=50, null=True, verbose_name='app名称')),
                ('applicant', models.CharField(blank=True, default='watson.wu', max_length=50, verbose_name='审批人')),
                ('create_time', models.DateField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('expiry_date', models.CharField(blank=True, default='permanent', max_length=50, verbose_name='过期时间')),
                ('commit_by', models.CharField(max_length=100, verbose_name='提交人')),
                ('action', models.CharField(blank=True, default='New Add', max_length=50, verbose_name='执行的动作')),
                ('comment', models.CharField(max_length=1000, verbose_name='备注')),
                ('workform_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workform.WorkFormModel', verbose_name='关联工单记录')),
            ],
            options={
                'verbose_name': '防火墙规则表',
                'db_table': 'firewall_rules',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='firewallrulesmodel',
            unique_together=set([('s_ip', 'd_ip', 'd_port', 'protocol')]),
        ),
    ]
