# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20180506_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='firewallrulesmodel',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='最后一次更新时间'),
        ),
        migrations.AddField(
            model_name='firewallrulesmodel',
            name='update_user',
            field=models.CharField(max_length=100, null=True, verbose_name='修改人'),
        ),
        migrations.AlterField(
            model_name='firewallrulesmodel',
            name='app_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='app名称'),
        ),
    ]
