# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-07 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20180507_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrulesmodel',
            name='d_ip',
            field=models.CharField(max_length=15, verbose_name='目标IP'),
        ),
        migrations.AlterField(
            model_name='firewallrulesmodel',
            name='s_ip',
            field=models.CharField(max_length=15, verbose_name='源IP'),
        ),
    ]
