# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-16 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20180507_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrulesmodel',
            name='action',
            field=models.CharField(max_length=50, verbose_name='执行的动作'),
        ),
        migrations.AlterField(
            model_name='firewallrulesmodel',
            name='applicant',
            field=models.CharField(max_length=50, verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='firewallrulesmodel',
            name='expiry_date',
            field=models.CharField(max_length=50, verbose_name='过期时间'),
        ),
    ]
