# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-20 11:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn_name', models.CharField(max_length=50, verbose_name='中文名')),
                ('role', models.CharField(choices=[('0', 'Head'), ('1', 'Controller'), ('2', 'Manager'), ('3', 'Employee')], default='3', max_length=10, verbose_name='角色')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号')),
                ('last_change_time', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='扩展用户表,与用户模型User建立一对一关系')),
            ],
            options={
                'verbose_name': '扩展用户表',
                'db_table': 'user_extend',
            },
        ),
    ]
